### ISSUE TITLE
didselectrowatindexpath is not working while clicking on the cell

### ISSUE THREAD

**Issue by hansrajgavali** [HighBay/PageMenu#177]
You had fixed this bug in the latest version but i am still getting this issue. I am not able to push a viewcontroller while clicking on the cell. what's the problem??

**Comment by csnu17** [comment]
You should use the parent navigation controller for pushing to another viewcontroller. See [this](https://github.com/HighBay/PageMenu/issues/200)

**Comment by hansrajgavali** [comment]
It worked thanks alot
