### ISSUE TITLE
reload Title of the PageMenu

### ISSUE THREAD

**Issue by anishparajuli555** [HighBay/PageMenu#198]
Since i have localization i need to reload the title only of PageMenu.How can i do that?below code is not updating 

```
  func  changeTheLanguageOfTabBartitleFunc() {
        pageMenu?.controllerArray[0].title = "Change"
        categoryController.title = "Change"
    
    }
```

**Comment by anishparajuli555** [comment]
` pageMenu?.menuItems[0].titleLabel?.text = "categories".localized()`

**Comment by brod-ie** [comment]
@anishparajuli555 There's no `menuItems` property on `pageMenu` for me?

**Comment by brod-ie** [comment]
Unless you edited the source and changed it to a public var?

**Comment by romk1n** [comment]
i am also interested in this ability since `menuItem` is not public
