### ISSUE TITLE
From Child view controller we can not able to push the controller to another one. 

### ISSUE THREAD

**Issue by ankitbansal806** [HighBay/PageMenu#200]
From Child view controller we can not able to push the controller to another one. 
I am using collection view in child view and if i set the action of push view controller in did select function the controller not push.
Please solve the issue.

**Comment by csnu17** [comment]
See the demo example 5. You have to set the child navigation controller to use the same navigation controller that parent controller is using.

**Comment by vikaskumar113** [comment]
hey csnu17,
can you describe it in obj c

**Comment by csnu17** [comment]
In ParentViewController.h (The view controller that it's include PageMenu)
```objective-c
childViewController = [storyboard instantiateViewControllerWithIdentifier:@"childViewController"];
childViewController.title = @"Child 1";
childViewController.parentNavigationController = self.navigationController;
[controllerArray addObject:childViewController];
```

In ChildViewController.h
```objective-c
@property (nonatomic, strong) UINavigationController *parentNavigationController;
```

When you want to push from ChildViewController to AnotherViewController you should use
```objective-c
[self.parentNavigationController pushViewController:anotherViewController animated:YES];
```

**Comment by vikaskumar113** [comment]
hey this was helpful
thankyou


On Thu, Mar 17, 2016 at 3:44 PM, Kittisak Phetrungnapha <
notifications@github.com> wrote:

> In ParentViewController.h (The view controller that it's include PageMenu)
>
> childViewController = [storyboard instantiateViewControllerWithIdentifier:@"childViewController"];
> childViewController.title = @"Child 1";
> childViewController.parentNavigationController = self.navigationController;
> [controllerArray addObject:childViewController];
>
> In ChildViewController.h
>
> @property (nonatomic, strong) UINavigationController *parentNavigationController;
>
> When you want to push from ChildViewController to AnotherViewController
> you should use
>
> [self.parentNavigationController pushViewController:anotherViewController animated:YES];
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/HighBay/PageMenu/issues/200#issuecomment-197802925>
>



-- 


*---------------------------Thanks & Regards*
*Vikas Rajput (**ios Developer)*
*Phone:7838869383*

**Comment by csnu17** [comment]
Thank you and please close this issue.

**Comment by ankitbansal806** [comment]
This was helpful.. Thanks csnu17 for help me out..

**Comment by hansrajgavali** [comment]
@csnu17 Hey thank you for your answer it worked perfectly

**Comment by JerryWang761208** [comment]
save my day !! really appreciate!

**Comment by SagarNikam688** [comment]
please can you please give it swift 3 with storyboard example

**Comment by ThakarRajesh** [comment]
Push View issue not resolved
parentNavigationController always return nil
Code
```
 arr = [[NSMutableArray alloc] init];
    SaveAdsSubViewController *controller1 = [[SaveAdsSubViewController alloc]initWithNibName:@"SaveAdsSubViewController" bundle:nil];
    controller1.title = @"Saved Ads";
    controller1.parentNavigationController = self.navigationController;
    [arr addObject:controller1];
    SavedViewController *controller2 = [[SavedViewController alloc]initWithNibName:@"SavedViewController" bundle:nil];
    controller2.title = @"Saved";
    controller2.parentNavigationController = self.navigationController;
     [arr addObject:controller2];
 _pageMenu = [[CAPSPageMenu alloc] initWithViewControllers:arr frame:CGRectMake(0.0, 0.0, self.view.frame.size.width, self.view.frame.size.height) options:parameters];
 [self.view addSubview:_pageMenu.view];
```

How to solved this issue @csnu17
