### ISSUE TITLE
SelectedItem background Color ...

### ISSUE THREAD

**Issue by skander300** [HighBay/PageMenu#232]
could i set a background color for the selected item ?

**Comment by linhtnn** [comment]
I have the same issue. Swift 3.

**Comment by bksasuke** [comment]
same issue. Please re-open this

**Comment by linhtnn** [comment]
Because in Swift 3, I use https://github.com/orazz/PageMenu version. But I can't see selectedItemBackgroundColor. Maybe author not update!
