### ISSUE TITLE
Is it possible to show content I built in my interface builder?

### ISSUE THREAD

**Issue by ameyavichare** [HighBay/PageMenu#260]
![screen shot 2016-08-04 at 4 31 38 pm](https://cloud.githubusercontent.com/assets/16960138/17399654/f75b19be-5a60-11e6-9910-19e99fb072be.png)

Is it possible to do something like this through PageMenu? I have my view controllers set up which have scrolling and multiple rows in it. I have built all this through the interface builder and auto layout. 
So can I use PageMenu for this as all I can see right now is a black screen even when I added few labels to the view controllers in the storyboard. Any suggestions are welcome!

**Comment by uyghurbeg** [comment]
You can add Navigationbar as childview.
